languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv-martopad"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://cv.martinlutheryung.com/"
title = "My CV"
#GoogleAnalytics = false

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#808080"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#808080"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#808080"
pages = 2
# Set this param to 'true' to swap the bar positions
swapColumns = false
